version: "3.7"

services:
  db:
    image: postgres:12
    container_name: local_development-db
    ports:
      - 5432:5432
    environment:
      # POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: funkycadet
      POSTGRES_PASSWORD: funkycadet
    # env_file:
    #   - .env
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
