[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij attach funkycadet || zellij"]
# args = ["-l", "-c", "zellij attach funkycadet || zellij"]

[font]
size = 12
# normal = { family = "MesloLGS NF", style = "Regular" }
# normal = { family = "JetBrains Mono", style = "Medium" }
normal = { family = "JetBrainsMono NF", style = "Medium" }

[window]
# startup_mode = "Maximized"
startup_mode = "Fullscreen"
opacity = 0.0
# blur = true
# decorations = "Full"
decorations_theme_variant = "Dark"

[env]
WINIT_X11_SCALE_FACTOR = '1.03125'
TERM = "xterm-256color"

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[terminal]

#background: '0x191919'
#foreground: '0xeaeaea'
